### ISSUE TITLE
'Open Git Project' hanging in Windows

### ISSUE THREAD

**Issue by leotm** [felipecaputo/git-project-manager#33]
I use GitHub Desktop so few projects in the default: ```C:\Users\leom\Documents\GitHub```

So added to _settings.json_: ```"gitProjectManager.baseProjectsFolders": [ "C:\\Users\\leom\\Documents\\GitHub" ]```.

I've tried adding option 1: ```"gitProjectManager.codePath": "C:\\Program Files (x86)\\Microsoft VS Code\\bin\\code.cmd"```

And replacing with option 2: ```"gitProjectManager.codePath" : { "windows": "C:\\Program Files (x86)\\Microsoft VS Code\\bin\\code.cmd" }```

And replacing with option 3: ```"gitProjectManager.codePath" : [ "C:\\Program Files (x86)\\Microsoft VS Code\\bin\\code.cmd" ]```

But still just hangs searching for the Git Projects :(

Any ideas?

Cheers

---

OS: Windows 10 Ult x64
Git Project Manager: 1.0.0
VS Code: 1.7.2

**Comment by felipecaputo** [comment]
Hi @leotm , could you please provide a screenshot of the vscode interface, including the statusbar and the Output  Panel (Ctrl+Shift+U on windows)  showing extension logs

Example:
![image](https://cloud.githubusercontent.com/assets/7751449/20576213/27d5b2ee-b1a4-11e6-82e2-0a8c105dd1f9.png)

**Comment by Tyriar** [comment]
Maybe `maxDepthRecursion` was too large? @felipecaputo should the default be lower than 4? 4 would probably include `node_modules` sub-directories for example. 

On a personal note I use 2 as I lay out my git dir as `~/dev/<user>/<project>`

**Comment by felipecaputo** [comment]
Good idea @Tyriar, I'll reduce there and I'll also let checkRemoteOrigin to false by default.

**Comment by felipecaputo** [comment]
Good idea @Tyriar, I'll reduce there and I'll also let checkRemoteOrigin to false by default.

**Comment by schwaerz** [comment]
Same issue here. Looks like there's still some information missing?

For me the git project manager configuration is

    "gitProjectManager.baseProjectsFolders": ["c:\\repositories"],
    "gitProjectManager.codePath": "C:\\Program Files (x86)\\Microsoft VS Code\\bin\\code.cmd",
    "gitProjectManager.maxDepthRecursion": 1,
    "gitProjectManager.checkRemoteOrigin": false

The extensions log doesn't show anything. Please find the screenshot attached.

![image](https://cloud.githubusercontent.com/assets/810086/23914630/d6a5af56-08e6-11e7-92a1-bbabde705288.png)

**Comment by felipecaputo** [comment]
Hi @schwaerz , it may be a problem with the max recursion, but can you try with maxDepthRecursion 2, maybe its considering 1 as the root directory. I'll take a look at this later today

**Comment by schwaerz** [comment]
Hi
thanks for the answer - and of course for providing this plugin :+1:  .

In fact first I tried with default recursion. After that I switched to 1 to see whether it fixes the issue.
But didn't try maxDepthRecursion 2. I'll give it a shot...
:gun:
... Unfortunately it didn't make a difference.
Thanks already for looking into it. This plugin finally would allow me to no longer depend on Atom editor :smirk:

**Comment by felipecaputo** [comment]
@schwaerz I will release another version today to fix issue to support open projects from subfolders, I'll add some logs and put a config to enable them.

After that let's make it work in no time!

**Comment by schwaerz** [comment]
Sounds great :+1:

**Comment by felipecaputo** [comment]
Hi @schwaerz, new version released. Could you please try it out?

**Comment by schwaerz** [comment]
Hi & thanks for the quick release.

Unfortunately I've to tell that it didn't fix my issue. Probably I just didn't wait long enough?

For testing I created a new folder with just two empty repositories in it. This works as expected.

I've got 43 repositories in my c:/repositories folder (all on local SSD).
Is there a way to do the scanning for the folders in the background? Otherwise I may touch my keyboard for indefinite amount of time ;)
How long do you thinks this should take at most? 

Thanks.

**Comment by schwaerz** [comment]
... Just found the root cause. Finally I remembered that c:\\repositories is just an NTFS junction to some other directory. Looks like this doesn't work here.
However if I enter the full path everything work like a charm :smile: 

Sorry for pointing you in the wrong direction. Think a small note like 'NTFS junctions are not supported' will do. Actually I don't need junction support.

Thanks for your support :+1:

**Comment by felipecaputo** [comment]
I'll try to take a look at NTFS junctions and how `fs` works on it, maybe it can be solved easily
