### ISSUE TITLE
Extension no longer works on Insiders (1.9)

### ISSUE THREAD

**Issue by Tyriar** [felipecaputo/git-project-manager#36]
See https://github.com/Microsoft/vscode/issues/18187

**Comment by felipecaputo** [comment]
I'll take a look at it tomorrow morning. I think I know what it is. Is the
open folder execute command promise. It has never failed before, so never
hit catch.

As soon as I figure out what it is I'll let you know.

Felipe Caputo

On Jan 6, 2017 1:16 PM, "Daniel Imms" <notifications@github.com> wrote:

See Microsoft/vscode#18187
<https://github.com/Microsoft/vscode/issues/18187>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/felipecaputo/git-project-manager/issues/36>, or mute
the thread

**Comment by Tyriar** [comment]
The linked issue explains you shouldn't assume executeCommand returns a promise, and I think the return value changed for that command.

**Comment by otbe** [comment]
I use the latest version of GPM in Insiders 1.11.0 and GPM does not work anymore. It reindexes the project folders after every restart of VSCode (with ```storeRepositoriesBetweenSessions``` turned on) and it does not open projects from the list via click/enter. Seems to be related to this issue!?

**Comment by Tyriar** [comment]
@otbe yes the extension appears broken now on today's insiders @ https://github.com/Microsoft/vscode/commit/5e9357bd5111eacf2b8fb39455c8afb5a42d632f

**Comment by otbe** [comment]
@Tyriar it started some days ago not today with your mentioned commit :)
But nevertheless Im happy this is confirmed.

**Comment by felipecaputo** [comment]
Hi @otbe and @Tyriar, I'll take a look on it today.

As soon as I find something I'll let you know

**Comment by Tyriar** [comment]
@felipecaputo this seems to have fixed itself, don't waste time investigating :smile:

**Comment by felipecaputo** [comment]
@Tyriar Thanks for the feedback! o/
