### ISSUE TITLE
Disambiguate entries with same remote but different folders

### ISSUE THREAD

**Issue by Tyriar** [felipecaputo/git-project-manager#80]
I have 2 folders cloned from Microsoft/vscode, they appear as the same entry in the quick pick:

![image](https://user-images.githubusercontent.com/2193314/43152152-9b942956-8f22-11e8-91b4-9cad02d5b417.png)

They're in `~/dev/vscode` and `~/dev/Microsoft/vscode`, maybe adding the path from the closest ancestor path to the label would work:

- vscode (dev)
- vscode (dev/Microsoft)

**Comment by KyrychukD** [comment]
I have a similar problem with a couple of local git repositories that do not have any remotes. By default they are displayed in the project picker like this:
![selection_065](https://user-images.githubusercontent.com/699961/45685262-7d13e100-bb51-11e8-96c2-758a472e8ea6.png)

I found that setting the `gitProjectManager.checkRemoteOrigin` setting to `false` makes the project picker display the project path instead of the `origin` remote URL:
![selection_066](https://user-images.githubusercontent.com/699961/45685350-c3694000-bb51-11e8-9e86-8c707416f5d4.png)

I would be nice if paths were displayed when there are projects with identical names or `origin` URL or when `origin` git remote is missing.

**Comment by felipecaputo** [comment]
@Tyriar can we close this with 1.7.0 released today with PR #84 ?

**Comment by Tyriar** [comment]
@felipecaputo works great 😃
