### ISSUE TITLE
Feature Request: Cache unsaved files when switching projects

### ISSUE THREAD

**Issue by DDriggs00** [felipecaputo/git-project-manager#89]
When switching between projects, it would be nice to keep all unsaved files cached (similar to when vs code is closed) and restored to the editor upon re-opening that project.

**Comment by DDriggs00** [comment]
That is correct. Currently with the latest release version, it asks you if you want to save, and if you don't, closes the files and switches projects. When you switch back, the unsaved files are not retained

**Comment by felipecaputo** [comment]
I was working on this and found that is by design, there is a configuration to change the behavior and keep dirty files between sessions on the same workspace.

Changing the configuration bellow will give you the behavior you expect.

![image](https://user-images.githubusercontent.com/7751449/46247261-3474e700-c3df-11e8-9e45-b404bea5aec0.png)


I'll leave this issue with a validation tag waiting for your feedback ;)

**Comment by DDriggs00** [comment]
Can validate that changing the "Hot Exit" setting from "OnExit" to "OnExitAndWindowClose" fixes the issue
